In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:

a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
addition=a+b
print("addition:",addition)
sub=a-b
print("subtraction:",sub)
multi=a*b
print("multiplication:",multi)
div=a/b
print("divisiion:",div)

addition: [11 22 33 44 55]
subtraction: [ 9 18 27 36 45]
multiplication: [ 10  40  90 160 250]
divisiion: [10. 10. 10. 10. 10.]


In [16]:
#minmax
marks=np.array([85,72,91,65,78,88])
max=marks.max()
min=marks.min()
avg=marks.mean()

In [13]:
max

np.int64(91)

In [14]:
min

np.int64(65)

In [17]:
avg

np.float64(79.83333333333333)

In [24]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
even=np.where(x%2==0)
print(even)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),)


In [27]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [28]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
y=x.reshape(3,4)

In [30]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])